apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubemq.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: api-port
    port: {{ .Values.service.apiPort }}
    protocol: TCP
    targetPort: 8080
  - name: grpc-port
    port: {{ .Values.service.grpcPort }}
    protocol: TCP
    targetPort: 50000
  - name: cluster-port
    port: {{ .Values.service.clusterPort }}
    protocol: TCP
    targetPort: 5228
  - name: rest-port
    port: {{ .Values.service.restPort }}
    protocol: TCP
    targetPort: 9090
  sessionAffinity: None
  selector:
    app: {{ include "kubemq.name" . }}
